plex:
  #Plex, if you ever make an official plex image, let me know.

  build: plex

  environment:
    - PLEX_VERSION=0.9.11.16.958-80f1748

  ports:
   - "32400:32400"

nzbget:

  build: nzbget

  environment:
    - NZBGET_VER=14.2

  ports:
    - "6789:6789"

sonarr:
  # Sonarr is pulled from an image since it's referenced in the official site
  # https://github.com/Sonarr/Sonarr/wiki/Installation#linux

  image: tuxeh/sonarr
  links:
    - nzbget
  ports:
    - "8989:8989"

couchpotato:
  build: couchpotato
  ports:
    - "5050:5050"
