plex:
  #Plex, if you ever make an official plex image, let me know.

  build: plex
  ports:
   - "32400:32400"

nzbget:
  # nzbget is installed from the ubuntu repositores

  build: nzbget
  ports:
    - "6789:6789"

sonarr:
  # Sonarr is pulled from an image since it's referenced in the official site
  # https://github.com/Sonarr/Sonarr/wiki/Installation#linux

  image: tuxeh/sonarr
  links:
    - nzbget
  ports:
    - "8989:8989"

couchpotato:
  build: couchpotato
  ports:
    - "5050:5050"
